project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Monitoring"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - topics.qmd        
        - text: "---"
        - topics/review-azure-monitor-capabilities.qmd
        - text: "---"       
        - topics/identify-data-sources-and-access-method.qmd
        - text: "---"
        - topics/what-is-log-analytics.qmd
        - text: "---"
        - topics/considerations-for-workspace-access-control.qmd  
        - text: "---"
        - topics/considerations-for-access-mode.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
