---
title: "Considerations for Access Mode"
css: ../styles.css
---

Source: [Logging and Monitoring](https://microsoftlearning.github.io/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions/Instructions/CaseStudy/08-Logging.html)

# Considerations for Access Mode
The access mode is how a user accesses the workspace and what data they can access.

|Issue|Workspace-context|Resource-context|
|---|---|---|
|How does the access mode work?|- You can view logs in the workspace you have permission to.<br/>- Queries in this mode are scoped to all data in all tables in the workspace.<br/>- This is the access mode used when logs are accessed with the workspace as the scope.|- When you access the workspace for a particular resource, resource group, or subscription.<br/>- You can view logs for only resources in all tables that you have access to.<br/>- Queries in this mode are scoped to only data associated with that resource.|
|Who is each model intended for?|Central administration.|Application teams.|
|What does a user require to view logs?|Permissions to the workspace.|Read access to the rescue.|
|What is the scope of permissions?|Workspace.|Azure resource.|
